(executable
 (public_name oca)
 (name oca)
 (modules oca)
 (libraries meta syntax))

(library
  (name syntax)
  (modules parser lexer ast)
  (libraries uchar))

(library
 (name meta)
 (modules meta))

(library
 (name files)
 (modules files)
 (preprocess
  (pps ppx_string)))

(library
 (name graph)
 (modules graph))
